default_platform :ios

platform :ios do
  skip_docs

  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    configureApp
    scan
  end

  desc "Archives XDK Messenger"
  lane :archive do
    configureApp
    match(type: "enterprise")
    gym(export_method: "enterprise")
  end

  desc "Deploys XDK Messenger to HockeyApp"
  lane :deploy do
    configureApp
    prepareChangelog
    match(type: "enterprise")
    gym(export_method: "enterprise")
    hockey(notes: File.read("../VERSION-CHANGELOG.md"))
  end

  def configureApp
    puts "Configuring XDK Messenger..."
    require 'json'
    configuration = [{
      :name => ENV["LYRM_APP_NAME"],
      :app_id => ENV["LYRM_APP_ID"],
      :identity_provider_url => ENV["LYRM_IDENTITY_PROVIDER_URL"]
    }].to_json

    puts "Writing configuration to ../LayerConfiguration.json"
    File.open("../LayerConfiguration.json", "w") do |f|
      f.write configuration
    end
    puts "Done. Successfully configured XDK Messenger"
  end

  def prepareChangelog
    version = `/usr/libexec/PlistBuddy -c \"print :CFBundleShortVersionString\" ../Resources/Info.plist`

    should_print = false
    File.open("../VERSION-CHANGELOG.md", 'w') { |file|
      File.open("../CHANGELOG.md").each do |line|
        if line == "\#\# #{version}"
          should_print = true
          next
        end
        if should_print
          if line.start_with?("\#\# ")
            break
          end
          file.write(line)
        end
      end
    }
  end
end
