default_platform :ios

platform :ios do
  skip_docs

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    configureApp
    scan
  end

  desc "Deploys XDK Messenger to HockeyApp"
  lane :deploy do
    configureApp
    cert
    sigh

    # Circle CI handles setting the CODE_SIGN_IDENTITY
    gym(
      xcargs: {
        :PROVISIONING_PROFILE => ENV["LYRM_PROVISIONING_PROFILE"]
      }
    )
    hockey(
      notes: File.read("../CHANGELOG.md")
    )
  end

  def configureApp
    puts "Configuring XDK Messenger..."
    require 'json'
    configuration = [{
      :name => ENV["LYRM_APP_NAME"],
      :app_id => ENV["LYRM_APP_ID"],
      :identity_provider_url => ENV["LYRM_IDENTITY_PROVIDER_URL"]
    }].to_json

    puts "Writing configuration to ../LayerConfiguration.json"
    File.open("../LayerConfiguration.json", "w") do |f|
      f.write configuration
    end
    puts "Done. Successfully configured XDK Messenger"
  end
end
